# Funding options for StegoGen
# This is optional - remove this file if you don't want sponsorship options

# GitHub Sponsors
# github: [yourusername]

# Patreon
# patreon: yourusername

# Buy Me a Coffee
# ko_fi: yourusername

# Custom sponsorship link
# custom: ["https://yourwebsite.com/donate"]